### ISSUE TITLE
Snippet Container getting terminated in 10 sec 

### ISSUE THREAD

**Issue by pratiandevops** [prasmussen/glot-snippets#10]
when i'm running the glot-snippet container it's getting terminated in 10 to 12 sec after running below is the error message 
![SnippetError](https://user-images.githubusercontent.com/53594913/85922516-98bd2700-b8a1-11ea-84a0-834932393f0e.PNG)

can you help ?

**Comment by prasmussen** [comment]
This probably means it was unable to connect to the couchdb database

**Comment by pratiandevops** [comment]
but i added the environment variable where i given the details of couchdb user and password

**Comment by pratiandevops** [comment]
kindly help i'm unable to run glot-snippet due to above error

**Comment by pratiandevops** [comment]
> This probably means it was unable to connect to the couchdb database

i have added correct Env Variable in glot-snippet for making connection to couchdb. kindly help if you think any other issue is there ? or i'm missing something
