### ISSUE TITLE
Error on every request

### ISSUE THREAD

**Issue by javierprovecho** [prasmussen/glot-snippets#3]
Hello @prasmussen,

I had followed your instructions for compiling glot-snippets and glot-run, and while app runs with a few tweaks, it always return `HTTP 500` for each request. The error log is so cryptic. Here is an example:

(error doesn't have `\n` so everything is in a single line)

```
08:08:39.692 [error] Ranch listener http had connection process started with cowboy_protocol:start_link/4 at <0.782.0> exit with reason: [{reason,{noproc,{gen_server,call,[snippet_srv,{list_public_excl_untitled,{20,0}}]}}},{mfa,{snippets_resource,list,2}},{stacktrace,[{gen_server,call,2,[{file,"gen_server.erl"},{line,204}]},{snippets_resource,list_public,4,[{file,"src/resources/snippets_resource.erl"},{line,103}]},{snippets_resource,list,2,[{file,"src/resources/snippets_resource.erl"},{line,88}]},{cowboy_rest,call,3,[{file,"src/cowboy_rest.erl"},{line,976}]},{cowboy_rest,set_resp_body,2,[{file,"src/cowboy_rest.erl"},{line,858}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,442}]}]},{req,[{socket,#Port<0.7288>},{transport,ranch_tcp},{connection,keepalive},{pid,<0.782.0>},{method,<<"GET">>},{version,'HTTP/1.1'},{peer,{{10,168,3,1},50790}},{host,<<"snippets.glot.svc.cluster.local">>},{host_info,undefined},{port,80},{path,<<"/snippets">>},{path_info,undefined},{qs,<<"page=1&per_page=20&include_untitled=false">>},{qs_vals,undefined},{bindings,[]},{headers,[{<<"host">>,<<"snippets.glot.svc.cluster.local">>},{<<"accept-encoding">>,<<"gzip">>},{<<"content-type">>,<<"application/json">>},{<<"user-agent">>,<<"haskell wreq-0.4.1.0">>}]},{p_headers,[{<<"if-modified-since">>,undefined},{<<"if-none-match">>,undefined},{<<"if-unmodified-since">>,undefined},{<<"if-match">>,undefined},{<<"accept">>,undefined}]},{cookies,undefined},{meta,[{media_type,{<<"application">>,<<"json">>,'*'}},{charset,undefined}]},{body_state,waiting},{buffer,<<>>},{multipart,undefined},{resp_compress,false},{resp_state,waiting},{resp_headers,[{<<"content-type">>,[<<"application">>,<<"/">>,<<"json">>,<<>>]}]},{resp_body,<<>>},{onresponse,#Fun<http_util.log_response.4>}]},{state,{state,<<"anonymous">>,{1,20}}}]
```

CouchDB is running fine, but I'm thinking if it needs some kind of initialization. At first, I thought the problem was with the database connection chain, but I also saw a similar error on **glot-run** which doesn't use any database:

```
08:01:36.822 [error] Ranch listener http had connection process started with cowboy_protocol:start_link/4 at <0.1108.0> exit with reason: [{reason,{noproc,{gen_server,call,[language_srv,{list}]}}},{mfa,{language_resource,resource_exists,2}},{stacktrace,[{gen_server,call,2,[{file,"gen_server.erl"},{line,204}]},{language,list_names,0,[{file,"src/models/language.erl"},{line,49}]},{language,is_supported,1,[{file,"src/models/language.erl"},{line,35}]},{language_resource,resource_exists,2,[{file,"src/resources/language_resource.erl"},{line,34}]},{cowboy_rest,call,3,[{file,"src/cowboy_rest.erl"},{line,976}]},{cowboy_rest,expect,6,[{file,"src/cowboy_rest.erl"},{line,960}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,442}]}]},{req,[{socket,#Port<0.7380>},{transport,ranch_tcp},{connection,keepalive},{pid,<0.1108.0>},{method,<<"GET">>},{version,'HTTP/1.1'},{peer,{{10,168,3,1},41064}},{host,<<"run.glot.svc.cluster.local">>},{host_info,undefined},{port,80},{path,<<"/languages/bash">>},{path_info,undefined},{qs,<<>>},{qs_vals,undefined},{bindings,[{name,<<"bash">>}]},{headers,[{<<"host">>,<<"run.glot.svc.cluster.local">>},{<<"accept-encoding">>,<<"gzip">>},{<<"content-type">>,<<"application/json">>},{<<"user-agent">>,<<"haskell wreq-0.4.1.0">>}]},{p_headers,[{<<"accept">>,undefined}]},{cookies,undefined},{meta,[{media_type,{<<"application">>,<<"json">>,'*'}},{charset,undefined}]},{body_state,waiting},{buffer,<<>>},{multipart,undefined},{resp_compress,false},{resp_state,waiting},{resp_headers,[{<<"content-type">>,[<<"application">>,<<"/">>,<<"json">>,<<>>]}]},{resp_body,<<>>},{onresponse,#Fun<http_util.log_response.4>}]},{state,{state,undefined}}]
```

I'm using erlang 18. I forked your repos for making some tweaks to make it work. You can check them out here:

https://github.com/javierprovecho/glot-run
https://github.com/javierprovecho/glot-snippets
https://github.com/javierprovecho/glot-www

I also created Dockerfiles for quicker deployment. If you use Docker, you can pull the images from here and experiment the same errors I see:

```
docker pull javierprovecho/glot-run
docker pull javierprovecho/glot-snippets
docker pull javierprovecho/glot-www
```

I look forward to make your project easier to deploy.

Thanks in advance for your support.

**Comment by javierprovecho** [comment]
After a little investigation on my own, I found that some component is not correctly initialized somewhere. I wonder what differences exists between glot.io and open source code in this part...

```
start_link() ->
    gen_server:start_link({local, ?MODULE}, ?MODULE, [], []).
```

**Comment by prasmussen** [comment]
glot.io runs on the same code that is on github, but I have been using erlang 17 until now. I will update my build environment to erlang 18 and share the details. Thanks for updating the dependencies to be erlang 18 compatible, saves me some time :)

**Comment by prasmussen** [comment]
I have updated the deps and changed `make_release.sh` to use rebar3.
Running `make_release.sh` should create a glot-snippets.tar.gz and you should be able to deploy this file to a server (erlang not required on the server, is embedded in the release) and start the application with `./bin/glot foreground` or `./bin/glot start`. You do need to set the environment variables mentioned in the README before starting the application though.
Let me know how it goes.

**Comment by javierprovecho** [comment]
@prasmussen new script using `rebar3` worked great. I updated my docker images and reduced their size (`glot-run` and `glot-snippets` only) to no more than 30 MB (using Alpine Linux). I'll make some PR in the following days :wink: . Thank you for your quick response.
